// Code generated by ent, DO NOT EDIT.

package emailchallenge

import (
	"PasswordManager/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldLTE(FieldID, id))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldEQ(FieldCode, v))
}

// Expiry applies equality check predicate on the "expiry" field. It's identical to ExpiryEQ.
func Expiry(v time.Time) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldEQ(FieldExpiry, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldContainsFold(FieldCode, v))
}

// ExpiryEQ applies the EQ predicate on the "expiry" field.
func ExpiryEQ(v time.Time) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldEQ(FieldExpiry, v))
}

// ExpiryNEQ applies the NEQ predicate on the "expiry" field.
func ExpiryNEQ(v time.Time) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldNEQ(FieldExpiry, v))
}

// ExpiryIn applies the In predicate on the "expiry" field.
func ExpiryIn(vs ...time.Time) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldIn(FieldExpiry, vs...))
}

// ExpiryNotIn applies the NotIn predicate on the "expiry" field.
func ExpiryNotIn(vs ...time.Time) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldNotIn(FieldExpiry, vs...))
}

// ExpiryGT applies the GT predicate on the "expiry" field.
func ExpiryGT(v time.Time) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldGT(FieldExpiry, v))
}

// ExpiryGTE applies the GTE predicate on the "expiry" field.
func ExpiryGTE(v time.Time) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldGTE(FieldExpiry, v))
}

// ExpiryLT applies the LT predicate on the "expiry" field.
func ExpiryLT(v time.Time) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldLT(FieldExpiry, v))
}

// ExpiryLTE applies the LTE predicate on the "expiry" field.
func ExpiryLTE(v time.Time) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldLTE(FieldExpiry, v))
}

// ForEQ applies the EQ predicate on the "for" field.
func ForEQ(v For) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldEQ(FieldFor, v))
}

// ForNEQ applies the NEQ predicate on the "for" field.
func ForNEQ(v For) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldNEQ(FieldFor, v))
}

// ForIn applies the In predicate on the "for" field.
func ForIn(vs ...For) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldIn(FieldFor, vs...))
}

// ForNotIn applies the NotIn predicate on the "for" field.
func ForNotIn(vs ...For) predicate.EmailChallenge {
	return predicate.EmailChallenge(sql.FieldNotIn(FieldFor, vs...))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.EmailChallenge {
	return predicate.EmailChallenge(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.EmailChallenge {
	return predicate.EmailChallenge(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EmailChallenge) predicate.EmailChallenge {
	return predicate.EmailChallenge(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EmailChallenge) predicate.EmailChallenge {
	return predicate.EmailChallenge(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EmailChallenge) predicate.EmailChallenge {
	return predicate.EmailChallenge(func(s *sql.Selector) {
		p(s.Not())
	})
}
