// Code generated by ent, DO NOT EDIT.

package ent

import (
	"PasswordManager/ent/additionalfield"
	"PasswordManager/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AdditionalFieldDelete is the builder for deleting a AdditionalField entity.
type AdditionalFieldDelete struct {
	config
	hooks    []Hook
	mutation *AdditionalFieldMutation
}

// Where appends a list predicates to the AdditionalFieldDelete builder.
func (afd *AdditionalFieldDelete) Where(ps ...predicate.AdditionalField) *AdditionalFieldDelete {
	afd.mutation.Where(ps...)
	return afd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (afd *AdditionalFieldDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, AdditionalFieldMutation](ctx, afd.sqlExec, afd.mutation, afd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (afd *AdditionalFieldDelete) ExecX(ctx context.Context) int {
	n, err := afd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (afd *AdditionalFieldDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: additionalfield.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: additionalfield.FieldID,
			},
		},
	}
	if ps := afd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, afd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	afd.mutation.done = true
	return affected, err
}

// AdditionalFieldDeleteOne is the builder for deleting a single AdditionalField entity.
type AdditionalFieldDeleteOne struct {
	afd *AdditionalFieldDelete
}

// Where appends a list predicates to the AdditionalFieldDelete builder.
func (afdo *AdditionalFieldDeleteOne) Where(ps ...predicate.AdditionalField) *AdditionalFieldDeleteOne {
	afdo.afd.mutation.Where(ps...)
	return afdo
}

// Exec executes the deletion query.
func (afdo *AdditionalFieldDeleteOne) Exec(ctx context.Context) error {
	n, err := afdo.afd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{additionalfield.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (afdo *AdditionalFieldDeleteOne) ExecX(ctx context.Context) {
	if err := afdo.Exec(ctx); err != nil {
		panic(err)
	}
}
