// Code generated by ent, DO NOT EDIT.

package ent

import (
	"PasswordManager/ent/predicate"
	"PasswordManager/ent/webauthnchallenge"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WebAuthnChallengeDelete is the builder for deleting a WebAuthnChallenge entity.
type WebAuthnChallengeDelete struct {
	config
	hooks    []Hook
	mutation *WebAuthnChallengeMutation
}

// Where appends a list predicates to the WebAuthnChallengeDelete builder.
func (wacd *WebAuthnChallengeDelete) Where(ps ...predicate.WebAuthnChallenge) *WebAuthnChallengeDelete {
	wacd.mutation.Where(ps...)
	return wacd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (wacd *WebAuthnChallengeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, WebAuthnChallengeMutation](ctx, wacd.sqlExec, wacd.mutation, wacd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (wacd *WebAuthnChallengeDelete) ExecX(ctx context.Context) int {
	n, err := wacd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (wacd *WebAuthnChallengeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: webauthnchallenge.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: webauthnchallenge.FieldID,
			},
		},
	}
	if ps := wacd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, wacd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	wacd.mutation.done = true
	return affected, err
}

// WebAuthnChallengeDeleteOne is the builder for deleting a single WebAuthnChallenge entity.
type WebAuthnChallengeDeleteOne struct {
	wacd *WebAuthnChallengeDelete
}

// Where appends a list predicates to the WebAuthnChallengeDelete builder.
func (wacdo *WebAuthnChallengeDeleteOne) Where(ps ...predicate.WebAuthnChallenge) *WebAuthnChallengeDeleteOne {
	wacdo.wacd.mutation.Where(ps...)
	return wacdo
}

// Exec executes the deletion query.
func (wacdo *WebAuthnChallengeDeleteOne) Exec(ctx context.Context) error {
	n, err := wacdo.wacd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{webauthnchallenge.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (wacdo *WebAuthnChallengeDeleteOne) ExecX(ctx context.Context) {
	if err := wacdo.Exec(ctx); err != nil {
		panic(err)
	}
}
