// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AdditionalField is the predicate function for additionalfield builders.
type AdditionalField func(*sql.Selector)

// EmailChallenge is the predicate function for emailchallenge builders.
type EmailChallenge func(*sql.Selector)

// Password is the predicate function for password builders.
type Password func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// WebAuthnChallenge is the predicate function for webauthnchallenge builders.
type WebAuthnChallenge func(*sql.Selector)

// WebAuthnCredential is the predicate function for webauthncredential builders.
type WebAuthnCredential func(*sql.Selector)
